### ISSUE TITLE
Создать таблицу с проектами

### ISSUE THREAD

**Issue by madao-madao** [madao-madao/myprofile#10]
Создать таблицу projects: идентификатор, название, дата создания, дата изменения
Использовать только терминал

**Comment by madao-madao** [comment]
![Image](https://github.com/user-attachments/assets/e0e8dbae-9760-4de6-9ff0-19768ed4fc4b)

**Comment by InzukiOrg** [comment]
> ![Image](https://github.com/user-attachments/assets/e0e8dbae-9760-4de6-9ff0-19768ed4fc4b)

id: не может иметь значение нул, добавить автоинкремент

**Comment by madao-madao** [comment]
![Image](https://github.com/user-attachments/assets/b95f927a-ac8d-474c-bd82-767ca1ac6e60)
