### ISSUE TITLE
Создать форму регистрации

### ISSUE THREAD

**Issue by InzukiOrg** [madao-madao/myprofile#5]

**Comment by madao-madao** [comment]
https://github.com/madao-madao/myprofile/commit/c30961e1272a9cbc7dbe7f6c393093ba46f14955

**Comment by InzukiOrg** [comment]
> [c30961e](https://github.com/madao-madao/myprofile/commit/c30961e1272a9cbc7dbe7f6c393093ba46f14955)

Отписал в комментариях

**Comment by InzukiOrg** [comment]
Добавить атрибуты name для input'ов
